services:
  backend:
    build:
      context: .
      target: backend
    environment:
      DB_HOST: ${DB_HOST}
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_NAME: ${DB_NAME}
      NODE_ENV: ${NODE_ENV}

  frontend:
    build:
      context: .
      target: frontend
      args:
        - REACT_APP_API_URL=${REACT_APP_API_URL}
    ports:
      - "80:80"
    depends_on:
      - backend
